# 2장 파이썬 프로그래밍

## 2.2 Numpy와 Pandas

In [12]:
import numpy as np

In [13]:
list(range(10))
np.array(range(0,10))
np.arange(10)
np.arange(0,10,2)
list(np.arange(0,10,2))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 2, 4, 6, 8])

[0, 2, 4, 6, 8]

In [14]:
np.arange(10)
np.arange(0, 20, 2)
np.hstack([np.arange(10), np.arange(0, 20, 2)])
np.vstack([np.arange(10), np.arange(0, 20, 2)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  2,  4,  6,  8, 10, 12,
       14, 16, 18])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [15]:
%time s = sum([i for i in range(1,99999)])

%time s = np.arange(99999).sum()

Wall time: 5.99 ms
Wall time: 969 µs


In [16]:
np.random.seed(1357)
m = np.random.randint(1,100,12)
m

m.max()
m.min()
m.sum()
m.mean()
m.std()

array([52, 71, 72, 80, 72, 53, 71, 46, 68, 59, 55, 19])

80

19

718

59.833333333333336

15.836841716565697

In [17]:
m.argmin() 
m.argmax()
m.argsort()
np.argsort(-m)

11

3

array([11,  7,  0,  5, 10,  9,  8,  1,  6,  2,  4,  3], dtype=int64)

array([ 3,  2,  4,  1,  6,  8,  9, 10,  5,  0,  7, 11], dtype=int64)

In [18]:
m.shape
m.reshape(-1,1).shape

(12,)

(12, 1)

In [19]:
m
m.shape
mr = m.reshape(3,4)
mr

array([52, 71, 72, 80, 72, 53, 71, 46, 68, 59, 55, 19])

(12,)

array([[52, 71, 72, 80],
       [72, 53, 71, 46],
       [68, 59, 55, 19]])

In [20]:
mr[2][3]
mr[0:2] 
mr[:, [1,2]]
mr[:, 0:3]
mr[:2, 2:]

19

array([[52, 71, 72, 80],
       [72, 53, 71, 46]])

array([[71, 72],
       [53, 71],
       [59, 55]])

array([[52, 71, 72],
       [72, 53, 71],
       [68, 59, 55]])

array([[72, 80],
       [71, 46]])

In [21]:
import pandas as pd
data = m.reshape((3,4))
pd.DataFrame(data)

0   1   2   3
0  52  71  72  80
1  72  53  71  46
2  68  59  55  19

In [22]:
index = range(1,4)
columns = ['A','B','C','D']
df = pd.DataFrame(data, index = index, columns = columns)
df

A   B   C   D
1  52  71  72  80
2  72  53  71  46
3  68  59  55  19

In [26]:
df.loc[2]
df.iloc[1]
df.loc[2, 'B']
df.iloc[1, 1]

A    72
B    53
C    71
D    46
Name: 2, dtype: int32

A    72
B    53
C    71
D    46
Name: 2, dtype: int32

53

53

In [27]:
df['A']
type(df['A'])
df[['A','B']]
type(df[['A','B']])
df[['A','B']].loc[2]

1    52
2    72
3    68
Name: A, dtype: int32

pandas.core.series.Series

A   B
1  52  71
2  72  53
3  68  59

pandas.core.frame.DataFrame

A    72
B    53
Name: 2, dtype: int32

In [28]:
df[1:]
df[-1:]

A   B   C   D
2  72  53  71  46
3  68  59  55  19

A   B   C   D
3  68  59  55  19

In [29]:
df['A']
df.A

1    52
2    72
3    68
Name: A, dtype: int32

1    52
2    72
3    68
Name: A, dtype: int32

In [30]:
df>=60
df[df>=60]
np.array(df>=60)*1 # (df>=60).values*1
pd.DataFrame(np.array(df>=60)*1, index = index, columns = columns)

A      B      C      D
1  False   True   True   True
2   True  False   True  False
3   True  False  False  False

A     B     C     D
1   NaN  71.0  72.0  80.0
2  72.0   NaN  71.0   NaN
3  68.0   NaN   NaN   NaN

array([[0, 1, 1, 1],
       [1, 0, 1, 0],
       [1, 0, 0, 0]])

A  B  C  D
1  0  1  1  1
2  1  0  1  0
3  1  0  0  0

In [31]:
df[df['C']>60]
df[(df['B']>50)&(df['C']<70)]

A   B   C   D
1  52  71  72  80
2  72  53  71  46

A   B   C   D
3  68  59  55  19

In [32]:
df = df[df>60].copy()
df['E'] = ['owl', 'fox', 'owl']
df
df.isnull().sum()
df.nunique()
df.dtypes

A     B     C     D    E
1   NaN  71.0  72.0  80.0  owl
2  72.0   NaN  71.0   NaN  fox
3  68.0   NaN   NaN   NaN  owl

A    1
B    2
C    1
D    2
E    0
dtype: int64

A    2
B    1
C    2
D    1
E    2
dtype: int64

A    float64
B    float64
C    float64
D    float64
E     object
dtype: object

In [33]:
type(df.isnull().sum()); df.isnull().sum().shape
type(df.nunique()); df.nunique().shape
type(df.dtypes); df.dtypes.shape

pandas.core.series.Series

(5,)

pandas.core.series.Series

(5,)

pandas.core.series.Series

(5,)

In [34]:
df.fillna(0)
df.fillna(0, inplace = True)  # df = df.fillna(0)
df

A     B     C     D    E
1   0.0  71.0  72.0  80.0  owl
2  72.0   0.0  71.0   0.0  fox
3  68.0   0.0   0.0   0.0  owl

A     B     C     D    E
1   0.0  71.0  72.0  80.0  owl
2  72.0   0.0  71.0   0.0  fox
3  68.0   0.0   0.0   0.0  owl

In [35]:
df = pd.DataFrame(mr, index = [i for i in 'abc'], columns = ['A','B','C','D'])
df
df.drop('c')
df.drop(['a', 'c'])

A   B   C   D
a  52  71  72  80
b  72  53  71  46
c  68  59  55  19

A   B   C   D
a  52  71  72  80
b  72  53  71  46

A   B   C   D
b  72  53  71  46

In [36]:
df.drop('C', axis=1)
df.drop(['A', 'C'], axis=1)

A   B   D
a  52  71  80
b  72  53  46
c  68  59  19

B   D
a  71  80
b  53  46
c  59  19

In [37]:
df.loc['d'] = df.loc['b']
df
df.duplicated()
df[~df.duplicated()]

A   B   C   D
a  52  71  72  80
b  72  53  71  46
c  68  59  55  19
d  72  53  71  46

a    False
b    False
c    False
d     True
dtype: bool

A   B   C   D
a  52  71  72  80
b  72  53  71  46
c  68  59  55  19